[tool.poetry]
name = "solvis-graphql-api"
version = "0.8.6"
description = "Graphql API for analysis of opensha modular Inversion Solutions"
authors = ["Chris Chamberlain <chrisbc@artisan.co.nz>"]
license = "AGPL3"
readme = "README.md"

classifiers=[
    'Development Status :: 2 - Pre-Alpha',
    'Intended Audience :: Developers',
    'License :: OSI Approved :: GNU General Public License v3 (GPLv3)',
    'Natural Language :: English',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
]
packages = [{include = "solvis_graphql_api"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
Flask = "^2.1.2"
Flask-Cors = "^3.0.10"
Flask-GraphQL = "^2.0.1"
graphene = "<3"
pyyaml = "^6.0"

nzshm-model = ">=0.6.0"
nzshm-common = ">=0.7.0"
solvis-store = {git = "https://github.com/GNS-Science/solvis-store", rev = "v2.0.4"}

matplotlib = "^3.7.1"
werkzeug = "^2.3.3"

# see https://github.com/orgs/python-poetry/discussions/7937
urllib3 = "<2"
numpy = "<1.25"
solvis = "^0.12.3"

[tool.poetry.group.dev.dependencies]
tox = ">=4.0"
black  = { version = "^22.3"}
isort  = { version = "^5.8.0"}
flake8  = { version = "^3.9.2"}
flake8-docstrings = { version = "^1.6.0", optional = true }
mypy = {version = "^1.10"}
pytest = { version = "^6.2.4"}
pytest-cov  = { version = "^2.12.0"}

virtualenv  = { version = "^20.2.2", optional = true}
pip  = { version = "^20.3.1", optional = true}

mkdocs  = { version = "^1.1.2"}
mkdocs-include-markdown-plugin  = { version = "^1.0.0"}
mkdocs-material  = { version = "^6.1.7"}
mkdocs-material-extensions  = { version = "^1.0.1"}
mkdocs-autorefs = {version = "^0.3.1"}

pymdown-extensions = {version = "^9.4"}
mkdocs-pymdownx-material-extras = "^2.0.3"

twine  = { version = "^3.3.0"}

pre-commit = {version = "^2.12.0", optional = true}
toml = {version = "^0.10.2", optional = true}
bump2version = {version = "^1.0.1"}
jinja2 = {version = "3.0.3"}
types-python-dateutil = "^2.8.16"
types-PyYAML = "^6.0.7"
moto = "^4.0.2"



[tool.poetry.group.doc.dependencies]
mkdocstrings-python = "^1.10.5"

[tool.poetry.extras]
test = [
    "pytest",
    "black",
    "isort",
    "mypy",
    "flake8",
    "flake8-docstrings",
    "pytest-cov"
    ]

dev = ["tox", "pre-commit", "virtualenv", "pip", "twine", "toml", "bump2version"]

doc = [
    "mkdocs",
    "mkdocs-include-markdown-plugin",
    "mkdocs-material",
    "mkdocstrings",
    "mkdocs-material-extension",
    "mkdocs-autorefs"
    ]

[tool.black]
line-length = 120
skip-string-normalization = true
target-version = ['py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 120
skip_gitignore = true
# you can skip files as below
#skip_glob = docs/conf.py



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
